### PR TITLE
Change file mode of internal/libsass/* from 0755 to 0644

### PR DESCRIPTION
**Pull request by anthonyfok**
Fixes Lintian warning: executable-not-elf-or-script

----

Appendix: `lintian -i --no-tag-display-limit` output:

```
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast.cpp
N: 
N:    This executable file is not an ELF format binary, and does not start
N:    with the #! sequence that marks interpreted scripts. It might be a sh
N:    script that fails to name /bin/sh as its shell, or it may be incorrectly
N:    marked as executable. Sometimes upstream files developed on Windows are
N:    marked unnecessarily as executable on other systems.
N:    
N:    If you are using debhelper to build your package, running dh_fixperms
N:    will often correct this problem for you.
N:    
N:    Refer to Debian Policy Manual section 10.4 (Scripts) for details.
N:    
N:    Severity: normal, Certainty: certain
N:    
N:    Check: scripts, Type: binary
N: 
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast2c.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast2c.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast_def_macros.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast_fwd_decl.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast_fwd_decl.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast_helpers.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast_sel_cmp.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast_sel_super.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast_sel_unify.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast_sel_weave.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast_selectors.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast_selectors.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast_supports.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast_supports.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast_values.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ast_values.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/backtrace.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/backtrace.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/base64vlq.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/base64vlq.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/bind.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/bind.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/c2ast.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/c2ast.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/c99func.c
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/cencode.c
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/check_nesting.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/check_nesting.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/color_maps.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/color_maps.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/constants.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/constants.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/context.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/context.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/cssize.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/cssize.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/dart_helpers.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/debug.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/debugger.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/emitter.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/emitter.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/environment.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/environment.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/error_handling.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/error_handling.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/eval.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/eval.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/eval_selectors.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/expand.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/expand.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/extender.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/extender.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/extension.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/extension.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/file.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/file.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_colors.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_colors.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_lists.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_lists.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_maps.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_maps.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_miscs.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_miscs.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_numbers.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_numbers.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_selectors.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_selectors.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_strings.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_strings.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_utils.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/fn_utils.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/inspect.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/inspect.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/json.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/json.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/kwd_arg_macros.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/lexer.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/lexer.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/listize.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/listize.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/mapping.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/operation.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/operators.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/operators.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/ordered_map.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/output.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/output.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/parser.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/parser.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/parser_selectors.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/permutate.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/plugins.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/plugins.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/position.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/position.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/prelexer.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/prelexer.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/remove_placeholders.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/remove_placeholders.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/sass.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/sass.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/sass2scss.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/sass_context.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/sass_context.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/sass_functions.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/sass_functions.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/sass_values.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/sass_values.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/source_map.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/source_map.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/stylesheet.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/stylesheet.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/to_value.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/to_value.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/units.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/units.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/utf8.h
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/utf8_string.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/utf8_string.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/util.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/util.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/util_string.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/util_string.hpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/values.cpp
W: golang-github-bep-golibsass-dev: executable-not-elf-or-script usr/share/gocode/src/github.com/bep/golibsass/internal/libsass/values.hpp
```

### CODE REVIEW

**Comment by bep** [comment]
Thanks; question, what happens when I run `pull-libsass.sh some-version`?

**Comment by anthonyfok** [comment]
> Thanks; question, what happens when I run `pull-libsass.sh some-version`?

It would update the files in the subtree placed in the libsass_src/ directory.

It would not touch the files related to this pull request because the internal/ directory is not touched by the `pull-libsass.sh` command.

internal/libsass/*.{c,h,cpp,hpp} are just 3-line stub files that are automatically generated... Oh, I see what you mean!  They are generated by `go run gen/main.go`!  I'd better fix `gen/main.go` too and make another push to this PR.  Be right back.

**Comment by anthonyfok** [comment]
I changed all occurrences of `0755` (used in `ioutil.WriteFile()`) in Go code to `0644` as they look like wrapper header files and test CSS files, i.e. non-executable files.
Please check to make sure I didn't break anything.  Thanks!

**Comment by bep** [comment]
Looks good, any breakage will break the build when it arrives in Hugo.

**Pull request merged**
